plugins {
  id 'java'
  id 'java-library'
  id 'maven-publish'
  id 'signing'
  id 'com.diffplug.spotless' version "8.10.1"
}

group = 'org.synyx'
version = project.hasProperty('version') ? project.version : 'dev'

repositories {
  mavenCentral()
}

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(21))
  }
  withJavadocJar()
  withSourcesJar()
}

dependencies {
  implementation 'com.fasterxml.jackson.core:jackson-core:[2.17.0,)'
  implementation 'com.fasterxml.jackson.core:jackson-databind:[2.17.0,)'
  implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:[2.17.0,)'
  implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:[2.17.0,)'

  implementation 'org.slf4j:slf4j-api:[2.0.0,)'

  testImplementation platform('org.junit:junit-bom:6.1.3')
  testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
  useJUnitPlatform()
}

publishing {
  publications {
    javaMatrixBotLib(MavenPublication) {
      from components.java
      pom {
        name = "Java Matrix Bot Lib"
        description = "Library proving an API to interact with a matrix server as a bot."
        url = "https://github.com/synyx/java-matrix-bot-lib"
        licenses {
          license {
            name = 'The Apache License, Version 2.0'
            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
          }
        }
        developers {
          developer {
            id = 'synyx'
            name = 'synyx Developer'
            email = 'mavencentral+java-matrix-bot-lib@synyx.de'
            organization = 'synyx'
            organizationUrl = 'https://synyx.de'
          }
        }
        scm {
          connection = 'scm:git:git://github.com/synyx/java-matrix-bot-lib.git'
          developerConnection = 'scm:git:ssh://github.com:synyx/java-matrix-bot-lib.git'
          url = 'https://github.com/synyx/java-matrix-bot-lib'
        }
      }
    }
  }

  repositories {
    maven {
      name = "LocalMavenWithChecksums"
      url = uri(layout.buildDirectory.dir("staging-deploy"))
    }
  }
}

signing {
  useGpgCmd()
  sign publishing.publications.javaMatrixBotLib
}

spotless {
  groovyGradle {
    greclipse()
    trimTrailingWhitespace()
    leadingTabsToSpaces(2)
    endWithNewline()
  }
  java {
    googleJavaFormat('1.33.0').reflowLongStrings()
    importOrder()
    removeUnusedImports()
    forbidWildcardImports()
    formatAnnotations()
  }
}
